### ISSUE TITLE
How can you resize a texture?

### ISSUE THREAD

**Issue by tgodoib** [SilverTiger/lwjgl3-tutorial#11]
I am having some issues trying to resize and image, i tryed to use the glScalef but it gives this error: A function that is not available in the current context was called.
Should I use this function? And so how and where do I use it?

**Comment by SilverTiger** [comment]
`glScale` can only be used with deprecated OpenGL. In the modern way you have to multiply a scale matrix, when creating the MVP matrix, e.g. by using a scale matrix instead of the identity matrix as model matrix. But this would scale the whole screen.

For scaling a single object you just have to change the width and height of that object to your desired size. The texture coordinates remain unchanged.
